[package]
name = "server-background"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
common = { path = "../common" }
tracing = { workspace = true }
async-channel = { workspace = true }
