env_files = [{ path = "../env/dev.env", profile = "development" }]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
workspace = false

[tasks.dev]
run_task = { name = ["start-mysql", "watch"] }
workspace = false

[tasks.watch]
command = "cargo"
args = ["run", "--bin", "server"]
watch = { watch = ["./packages/"] }
workspace = false

[tasks.migrate]
script_runner = "@duckscript"
script = '''
set_env DATABASE_URL ${DB_URL}/${DB_NAME}
exec sea-orm-cli migrate ${1}
'''
workspace = false

[tasks.start-mysql]
script_runner = "@duckscript"
script = '''
cd ./containers/mysql
exec docker-compose up -d
'''
workspace = false
