env_files = [{ path = "../env/dev.env", profile = "development" }]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
workspace = false

[tasks.build-profile]
env = { "CARGO_PROFILE_RELEASE_DEBUG" = "true" }
command = "cargo"
args = ["build", "--release"]
workspace = false

[tasks.start]
command = "./target/release/server"
workspace = false

[tasks.start-perf]
command = "sudo"
args = ["-E", "perf", "record", "--", "./target/release/server"]
workspace = false

[tasks.dev]
run_task = { name = ["start-db", "watch"] }
workspace = false

[tasks.dev-profile]
run_task = { name = ["start-db", "profile"] }
workspace = false

[tasks.watch]
command = "cargo"
args = ["run", "--bin", "server"]
watch = { watch = ["./packages/"] }
workspace = false

[tasks.profile]
env = { "CARGO_PROFILE_RELEASE_DEBUG" = "true" }
command = "cargo"
args = ["flamegraph", "--bin", "server", "--root"]
# watch = { watch = ["./packages/"] }
workspace = false

[tasks.migrate]
script = '''
#!@duckscript
cd packages/db
exec sea-orm-cli migrate ${1}
'''
workspace = false

[tasks.generate-entity]
script = '''
#!@duckscript
exec sea-orm-cli generate entity -o packages/db/entity/src/current
'''
workspace = false

[tasks.start-db]
script_runner = "@duckscript"
script = '''
cd ./containers/postgresql
exec docker-compose up -d
'''
workspace = false

[tasks.update-entity]
script_runner = "@duckscript"
script = '''
cd packages/db
exec sea-orm-cli migrate down
exec sea-orm-cli migrate up
exec sea-orm-cli generate entity -o entity/src/current
'''
workspace = false
