env_files = [{ path = "../env/dev.env", profile = "development" }]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
workspace = false

[tasks.dev]
run_task = { name = ["start-db", "watch"] }
workspace = false

[tasks.watch]
command = "cargo"
args = ["run", "--bin", "server"]
watch = { watch = ["./packages/"] }
workspace = false

[tasks.soc]
script = '''
#!@duckscript
args = array ${1} ${2} ${3} ${4} ${5}
args_string = array_join ${args} " "
cd packages
exec sea-orm-cli %{args_string}
'''
workspace = false

[tasks.soc-generate-entity]
script = '''
#!@duckscript
exec sea-orm-cli generate entity -o packages/entity/src/current
'''
workspace = false

[tasks.start-db]
script_runner = "@duckscript"
script = '''
cd ./containers/postgresql
exec docker-compose up -d
'''
workspace = false
