[package]
name = "subsonic-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
common = { path = "../../common" }
serde = { workspace = true }
async-trait = "0.1"
