//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

pub mod prelude;

pub mod album;
pub mod album_artist_relation;
pub mod artist;
pub mod artist_track_relation;
pub mod genres;
pub mod library;
pub mod track;
pub mod user;
