//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "artist")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub library_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::library::Entity",
        from = "Column::LibraryId",
        to = "super::library::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Library,
}

impl Related<super::library::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Library.def()
    }
}

impl Related<super::track::Entity> for Entity {
    fn to() -> RelationDef {
        super::artist_track_relation::Relation::Track.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::artist_track_relation::Relation::Artist.def().rev())
    }
}

impl Related<super::album::Entity> for Entity {
    fn to() -> RelationDef {
        super::album_artist_relation::Relation::Album.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::album_artist_relation::Relation::Artist.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
