//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

pub use super::album::Entity as Album;
pub use super::album_artist_relation::Entity as AlbumArtistRelation;
pub use super::artist::Entity as Artist;
pub use super::artist_track_relation::Entity as ArtistTrackRelation;
pub use super::genres::Entity as Genres;
pub use super::library::Entity as Library;
pub use super::track::Entity as Track;
pub use super::user::Entity as User;
