[package]
name = "streamer-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
common = { path = "../common" }
serde = { workspace = true }
async-trait = "0.1"
