[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
common = { path = "../common" }
serde = { workspace = true }
async-trait = "0.1"
sea-orm = { workspace = true }
entity = { path = "../db/entity" }
tracing = { workspace = true }
