[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
common = { path = "../common" }
serde = { workspace = true }
async-trait = "0.1"
sea-orm = { workspace = true }
entity = { path = "../db/entity" }
tracing = { workspace = true }
async-graphql = "5"
async-graphql-axum = "5"
aliri_axum = "0.2"
aliri = "0.6"
futures-util = "0.3"
jsonwebtoken = "8"
once_cell = "1"
core = { path = "../core" }
uuid = { worksapce = true }
