version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - '${DATABASE_PORT}:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORTS: "${DATABASE_PORT}"
      PMA_USER: "${DATABASE_USER}"
      PMA_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "3002:80"
    volumes:
      - ./data/phpmyadmin/sessions:/sessions
volumes:
  mysql_data:
